version: '3.8'
services:
  selenium:
    image: seleniarm/standalone-chromium:117.0
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=60
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
