# JWT Ayarlar?
jwt.gizli-anahtar=kariyerYonetimSistemiIcinCokGizliBirAnahtar
jwt.jwt-sure=86400000
jwt.jwt-baslik=Authorization
jwt.jwt-baslangic=Bearer 

# CORS Ayarlar?
cors.izinli-kaynaklar=*

# Loglama
logging.level.org.springframework.web=DEBUG
logging.level.com.example.careermanagement=DEBUG

# Veritaban?
spring.datasource.url=jdbc:postgresql://localhost:5432/career_management
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Sunucu
server.port=8080

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html